package controllers.api

import controllers.ActionContext
import controllers.ActionContextPreparer
import controllers.RequestParameterTrait
import mpff.controllers.MPFFAbstractAPIController

class AbstractAPI extends MPFFAbstractAPIController[ActionContext] with RequestParameterTrait with ActionContextPreparer


