package controllers.api

import mpff.controllers.MPFFAbstractAPIController
import controllers.ActionContext
import controllers.RequestParameterTrait
import controllers.ActionContextPreparer

class AbstractAPI extends MPFFAbstractAPIController[ActionContext] with RequestParameterTrait with ActionContextPreparer


