package controllers.action

import mpff.controllers.controllers.action.MPFFAbstractActionController
import controllers.ActionContext
import controllers.RequestParameterTrait
import controllers.ActionContextPreparer

class AbstractAction extends MPFFAbstractActionController[ActionContext] with RequestParameterTrait with ActionContextPreparer
